### Получить список всех аккаунтов
GET localhost:8080/api/v1/accounts


### Получить аккаунт по id
GET localhost:8080/api/v1/accounts/2


### Создать аккаунт
POST localhost:8080/api/v1/accounts
Content-Type: application/json

{
  "email": "maxim23@ya.ru"
}


### Изменить email
PUT localhost:8080/api/v1/accounts/6
Content-Type: application/json

{
  "email": "olyacotleta@icloud.ru"
}


### Удалить аккаунт
DELETE localhost:8080/api/v1/accounts/5


### Снять деньги
PUT localhost:8080/api/v1/transactions/take
Content-Type: application/json

{
  "myAccountId": 1,
  "amount": 3
}


### Положить деньги
PUT localhost:8080/api/v1/transactions/put
Content-Type: application/json

{
  "myAccountId": 4,
  "amount": 7
}


### Перевести деньги
PUT localhost:8080/api/v1/transactions/transfer
Content-Type: application/json

{
  "senderAccountId": 3,
  "receiverAccountId": 2,
  "amount": 50
}
